### ISSUE TITLE
Error compiling on RHEL 8.5

### ISSUE THREAD

**Issue by JanoutV** [jellevos/mpsu-ca#2]
Hello,
I tried compiling your project using `cargo build --release` and I am getting following error on my machine.

![image](https://user-images.githubusercontent.com/44194415/164263982-a1c122eb-b9db-4326-ae34-85ecc525d682.png)

cargo version: 1.54.0
OS: RHEL 8.5
Linux kernel version: 4.18.0-348.20.1.el8_5.x86_64 
CPU: Intel i7-8665U

**Comment by jellevos** [comment]
Hi! Thanks for communicating this error and the other about fasthash not building on M1. I did not get a notification for these issues, so please forgive me for the long response time. I will look into these problems.

**Comment by jellevos** [comment]
The problem here was that this project was using a nightly feature, so the stable release would not compile it. However, this feature is not used anymore so it should build on stable from now on.
